# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/src/qgis/python/console/console_settings.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsDialogPythonConsole(object):
    def setupUi(self, SettingsDialogPythonConsole):
        SettingsDialogPythonConsole.setObjectName("SettingsDialogPythonConsole")
        SettingsDialogPythonConsole.setWindowModality(QtCore.Qt.NonModal)
        SettingsDialogPythonConsole.resize(1055, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsDialogPythonConsole.sizePolicy().hasHeightForWidth())
        SettingsDialogPythonConsole.setSizePolicy(sizePolicy)
        SettingsDialogPythonConsole.setMinimumSize(QtCore.QSize(500, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        SettingsDialogPythonConsole.setFont(font)
        SettingsDialogPythonConsole.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(SettingsDialogPythonConsole)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mOptionsListWidget = QtWidgets.QListWidget(SettingsDialogPythonConsole)
        self.mOptionsListWidget.setMinimumSize(QtCore.QSize(58, 0))
        self.mOptionsListWidget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.mOptionsListWidget.setStyleSheet("background: #5C5C5C; color: white;")
        self.mOptionsListWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mOptionsListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mOptionsListWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.mOptionsListWidget.setIconSize(QtCore.QSize(32, 32))
        self.mOptionsListWidget.setTextElideMode(QtCore.Qt.ElideNone)
        self.mOptionsListWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.mOptionsListWidget.setWordWrap(True)
        self.mOptionsListWidget.setObjectName("mOptionsListWidget")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/themes/default/propertyicons/system.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.mOptionsListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon)
        self.mOptionsListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/themes/default/propertyicons/attributes.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.mOptionsListWidget.addItem(item)
        self.gridLayout_2.addWidget(self.mOptionsListWidget, 0, 0, 2, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(SettingsDialogPythonConsole)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.scrollArea = QtWidgets.QScrollArea(self.page)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 690, 525))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBoxFontColor = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxFontColor.sizePolicy().hasHeightForWidth())
        self.groupBoxFontColor.setSizePolicy(sizePolicy)
        self.groupBoxFontColor.setProperty("collapsed", True)
        self.groupBoxFontColor.setProperty("saveCollapsedState", True)
        self.groupBoxFontColor.setObjectName("groupBoxFontColor")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBoxFontColor)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.fontComboBox = QtWidgets.QFontComboBox(self.groupBoxFontColor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontComboBox.sizePolicy().hasHeightForWidth())
        self.fontComboBox.setSizePolicy(sizePolicy)
        self.fontComboBox.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.fontComboBox.setObjectName("fontComboBox")
        self.horizontalLayout.addWidget(self.fontComboBox)
        self.label_3 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.spinBox = QtWidgets.QSpinBox(self.groupBoxFontColor)
        self.spinBox.setMinimumSize(QtCore.QSize(51, 26))
        self.spinBox.setMaximumSize(QtCore.QSize(51, 26))
        self.spinBox.setMinimum(6)
        self.spinBox.setMaximum(99)
        self.spinBox.setProperty("value", 10)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.gridLayout_15.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_16 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 0, 0, 1, 1)
        self.defaultFontColor = QgsColorButton(self.groupBoxFontColor)
        self.defaultFontColor.setText("")
        self.defaultFontColor.setObjectName("defaultFontColor")
        self.gridLayout_8.addWidget(self.defaultFontColor, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 0, 2, 1, 1)
        self.keywordFontColor = QgsColorButton(self.groupBoxFontColor)
        self.keywordFontColor.setText("")
        self.keywordFontColor.setObjectName("keywordFontColor")
        self.gridLayout_8.addWidget(self.keywordFontColor, 0, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_26.setObjectName("label_26")
        self.gridLayout_8.addWidget(self.label_26, 0, 4, 1, 1)
        self.classFontColor = QgsColorButton(self.groupBoxFontColor)
        self.classFontColor.setText("")
        self.classFontColor.setObjectName("classFontColor")
        self.gridLayout_8.addWidget(self.classFontColor, 0, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 1, 0, 1, 1)
        self.methodFontColor = QgsColorButton(self.groupBoxFontColor)
        self.methodFontColor.setText("")
        self.methodFontColor.setObjectName("methodFontColor")
        self.gridLayout_8.addWidget(self.methodFontColor, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_18.setObjectName("label_18")
        self.gridLayout_8.addWidget(self.label_18, 1, 2, 1, 1)
        self.decorFontColor = QgsColorButton(self.groupBoxFontColor)
        self.decorFontColor.setText("")
        self.decorFontColor.setObjectName("decorFontColor")
        self.gridLayout_8.addWidget(self.decorFontColor, 1, 3, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_55.setObjectName("label_55")
        self.gridLayout_8.addWidget(self.label_55, 1, 4, 1, 1)
        self.numberFontColor = QgsColorButton(self.groupBoxFontColor)
        self.numberFontColor.setText("")
        self.numberFontColor.setObjectName("numberFontColor")
        self.gridLayout_8.addWidget(self.numberFontColor, 1, 5, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_19.setObjectName("label_19")
        self.gridLayout_8.addWidget(self.label_19, 2, 0, 1, 1)
        self.commentFontColor = QgsColorButton(self.groupBoxFontColor)
        self.commentFontColor.setText("")
        self.commentFontColor.setObjectName("commentFontColor")
        self.gridLayout_8.addWidget(self.commentFontColor, 2, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_20.setObjectName("label_20")
        self.gridLayout_8.addWidget(self.label_20, 2, 2, 1, 1)
        self.commentBlockFontColor = QgsColorButton(self.groupBoxFontColor)
        self.commentBlockFontColor.setText("")
        self.commentBlockFontColor.setObjectName("commentBlockFontColor")
        self.gridLayout_8.addWidget(self.commentBlockFontColor, 2, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_24.setObjectName("label_24")
        self.gridLayout_8.addWidget(self.label_24, 4, 4, 1, 1)
        self.cursorColor = QgsColorButton(self.groupBoxFontColor)
        self.cursorColor.setText("")
        self.cursorColor.setObjectName("cursorColor")
        self.gridLayout_8.addWidget(self.cursorColor, 4, 5, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_22.setObjectName("label_22")
        self.gridLayout_8.addWidget(self.label_22, 2, 4, 1, 1)
        self.caretLineColor = QgsColorButton(self.groupBoxFontColor)
        self.caretLineColor.setText("")
        self.caretLineColor.setObjectName("caretLineColor")
        self.gridLayout_8.addWidget(self.caretLineColor, 2, 5, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_28.setObjectName("label_28")
        self.gridLayout_8.addWidget(self.label_28, 3, 0, 1, 1)
        self.singleQuoteFontColor = QgsColorButton(self.groupBoxFontColor)
        self.singleQuoteFontColor.setText("")
        self.singleQuoteFontColor.setObjectName("singleQuoteFontColor")
        self.gridLayout_8.addWidget(self.singleQuoteFontColor, 3, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_31.setObjectName("label_31")
        self.gridLayout_8.addWidget(self.label_31, 3, 2, 1, 1)
        self.doubleQuoteFontColor = QgsColorButton(self.groupBoxFontColor)
        self.doubleQuoteFontColor.setText("")
        self.doubleQuoteFontColor.setObjectName("doubleQuoteFontColor")
        self.gridLayout_8.addWidget(self.doubleQuoteFontColor, 3, 3, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_29.setObjectName("label_29")
        self.gridLayout_8.addWidget(self.label_29, 4, 0, 1, 1)
        self.tripleSingleQuoteFontColor = QgsColorButton(self.groupBoxFontColor)
        self.tripleSingleQuoteFontColor.setText("")
        self.tripleSingleQuoteFontColor.setObjectName("tripleSingleQuoteFontColor")
        self.gridLayout_8.addWidget(self.tripleSingleQuoteFontColor, 4, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_30.setObjectName("label_30")
        self.gridLayout_8.addWidget(self.label_30, 4, 2, 1, 1)
        self.tripleDoubleQuoteFontColor = QgsColorButton(self.groupBoxFontColor)
        self.tripleDoubleQuoteFontColor.setText("")
        self.tripleDoubleQuoteFontColor.setObjectName("tripleDoubleQuoteFontColor")
        self.gridLayout_8.addWidget(self.tripleDoubleQuoteFontColor, 4, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_15.setObjectName("label_15")
        self.gridLayout_8.addWidget(self.label_15, 3, 4, 1, 1)
        self.paperBackgroundColor = QgsColorButton(self.groupBoxFontColor)
        self.paperBackgroundColor.setText("")
        self.paperBackgroundColor.setObjectName("paperBackgroundColor")
        self.gridLayout_8.addWidget(self.paperBackgroundColor, 3, 5, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_42.setObjectName("label_42")
        self.gridLayout_8.addWidget(self.label_42, 5, 0, 1, 1)
        self.marginBackgroundColor = QgsColorButton(self.groupBoxFontColor)
        self.marginBackgroundColor.setText("")
        self.marginBackgroundColor.setObjectName("marginBackgroundColor")
        self.gridLayout_8.addWidget(self.marginBackgroundColor, 5, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_43.setObjectName("label_43")
        self.gridLayout_8.addWidget(self.label_43, 5, 2, 1, 1)
        self.marginForegroundColor = QgsColorButton(self.groupBoxFontColor)
        self.marginForegroundColor.setText("")
        self.marginForegroundColor.setObjectName("marginForegroundColor")
        self.gridLayout_8.addWidget(self.marginForegroundColor, 5, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 5, 4, 1, 1)
        self.stderrFontColor = QgsColorButton(self.groupBoxFontColor)
        self.stderrFontColor.setText("")
        self.stderrFontColor.setObjectName("stderrFontColor")
        self.gridLayout_8.addWidget(self.stderrFontColor, 5, 5, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_48.setObjectName("label_48")
        self.gridLayout_8.addWidget(self.label_48, 6, 0, 1, 1)
        self.selectionBackgroundColor = QgsColorButton(self.groupBoxFontColor)
        self.selectionBackgroundColor.setText("")
        self.selectionBackgroundColor.setObjectName("selectionBackgroundColor")
        self.gridLayout_8.addWidget(self.selectionBackgroundColor, 6, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_49.setObjectName("label_49")
        self.gridLayout_8.addWidget(self.label_49, 6, 2, 1, 1)
        self.selectionForegroundColor = QgsColorButton(self.groupBoxFontColor)
        self.selectionForegroundColor.setText("")
        self.selectionForegroundColor.setObjectName("selectionForegroundColor")
        self.gridLayout_8.addWidget(self.selectionForegroundColor, 6, 3, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_50.setObjectName("label_50")
        self.gridLayout_8.addWidget(self.label_50, 7, 0, 1, 1)
        self.matchedBraceBackgroundColor = QgsColorButton(self.groupBoxFontColor)
        self.matchedBraceBackgroundColor.setText("")
        self.matchedBraceBackgroundColor.setObjectName("matchedBraceBackgroundColor")
        self.gridLayout_8.addWidget(self.matchedBraceBackgroundColor, 7, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.groupBoxFontColor)
        self.label_60.setObjectName("label_60")
        self.gridLayout_8.addWidget(self.label_60, 7, 2, 1, 1)
        self.matchedBraceForegroundColor = QgsColorButton(self.groupBoxFontColor)
        self.matchedBraceForegroundColor.setText("")
        self.matchedBraceForegroundColor.setObjectName("matchedBraceForegroundColor")
        self.gridLayout_8.addWidget(self.matchedBraceForegroundColor, 7, 3, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.resetFontColor = QtWidgets.QToolButton(self.groupBoxFontColor)
        self.resetFontColor.setText("")
        self.resetFontColor.setAutoRaise(True)
        self.resetFontColor.setObjectName("resetFontColor")
        self.verticalLayout_4.addWidget(self.resetFontColor)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.gridLayout_15.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.gridLayout_9.addWidget(self.groupBoxFontColor, 0, 0, 1, 1)
        self.groupBoxAutoCompletion = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxAutoCompletion.setCheckable(True)
        self.groupBoxAutoCompletion.setChecked(True)
        self.groupBoxAutoCompletion.setProperty("collapsed", False)
        self.groupBoxAutoCompletion.setProperty("saveCheckedState", True)
        self.groupBoxAutoCompletion.setProperty("saveCollapsedState", True)
        self.groupBoxAutoCompletion.setObjectName("groupBoxAutoCompletion")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBoxAutoCompletion)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_6 = QtWidgets.QLabel(self.groupBoxAutoCompletion)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.autoCompThreshold = QtWidgets.QSpinBox(self.groupBoxAutoCompletion)
        self.autoCompThreshold.setMaximum(10)
        self.autoCompThreshold.setProperty("value", 2)
        self.autoCompThreshold.setObjectName("autoCompThreshold")
        self.gridLayout_5.addWidget(self.autoCompThreshold, 0, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBoxAutoCompletion)
        self.label_36.setObjectName("label_36")
        self.gridLayout_5.addWidget(self.label_36, 0, 2, 1, 1)
        self.layoutRadioButton = QtWidgets.QGridLayout()
        self.layoutRadioButton.setObjectName("layoutRadioButton")
        self.autoCompFromDocAPI = QtWidgets.QRadioButton(self.groupBoxAutoCompletion)
        self.autoCompFromDocAPI.setObjectName("autoCompFromDocAPI")
        self.layoutRadioButton.addWidget(self.autoCompFromDocAPI, 0, 2, 1, 1)
        self.autoCompFromAPI = QtWidgets.QRadioButton(self.groupBoxAutoCompletion)
        self.autoCompFromAPI.setChecked(True)
        self.autoCompFromAPI.setObjectName("autoCompFromAPI")
        self.layoutRadioButton.addWidget(self.autoCompFromAPI, 0, 1, 1, 1)
        self.autoCompFromDoc = QtWidgets.QRadioButton(self.groupBoxAutoCompletion)
        self.autoCompFromDoc.setObjectName("autoCompFromDoc")
        self.layoutRadioButton.addWidget(self.autoCompFromDoc, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.layoutRadioButton, 1, 0, 1, 3)
        self.gridLayout_9.addWidget(self.groupBoxAutoCompletion, 1, 0, 1, 1)
        self.groupBox_4 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setProperty("collapsed", True)
        self.groupBox_4.setProperty("saveCollapsedState", True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.autoCloseBracket = QtWidgets.QCheckBox(self.groupBox_4)
        self.autoCloseBracket.setObjectName("autoCloseBracket")
        self.verticalLayout_2.addWidget(self.autoCloseBracket)
        self.autoInsertionImport = QtWidgets.QCheckBox(self.groupBox_4)
        self.autoInsertionImport.setObjectName("autoInsertionImport")
        self.verticalLayout_2.addWidget(self.autoInsertionImport)
        self.gridLayout_11.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_4, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem1, 3, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_18.addWidget(self.scrollArea, 0, 0, 2, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 690, 525))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBoxRunDebugEditor = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxRunDebugEditor.sizePolicy().hasHeightForWidth())
        self.groupBoxRunDebugEditor.setSizePolicy(sizePolicy)
        self.groupBoxRunDebugEditor.setProperty("collapsed", False)
        self.groupBoxRunDebugEditor.setProperty("saveCollapsedState", True)
        self.groupBoxRunDebugEditor.setObjectName("groupBoxRunDebugEditor")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBoxRunDebugEditor)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.enableObjectInspector = QtWidgets.QCheckBox(self.groupBoxRunDebugEditor)
        self.enableObjectInspector.setChecked(False)
        self.enableObjectInspector.setObjectName("enableObjectInspector")
        self.gridLayout_14.addWidget(self.enableObjectInspector, 0, 0, 1, 1)
        self.autoSaveScript = QtWidgets.QCheckBox(self.groupBoxRunDebugEditor)
        self.autoSaveScript.setObjectName("autoSaveScript")
        self.gridLayout_14.addWidget(self.autoSaveScript, 1, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBoxRunDebugEditor, 0, 0, 1, 1)
        self.groupBoxFontColorEditor = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxFontColorEditor.sizePolicy().hasHeightForWidth())
        self.groupBoxFontColorEditor.setSizePolicy(sizePolicy)
        self.groupBoxFontColorEditor.setProperty("collapsed", False)
        self.groupBoxFontColorEditor.setProperty("saveCollapsedState", True)
        self.groupBoxFontColorEditor.setObjectName("groupBoxFontColorEditor")
        self.gridLayout_141 = QtWidgets.QGridLayout(self.groupBoxFontColorEditor)
        self.gridLayout_141.setObjectName("gridLayout_141")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.fontComboBoxEditor = QtWidgets.QFontComboBox(self.groupBoxFontColorEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontComboBoxEditor.sizePolicy().hasHeightForWidth())
        self.fontComboBoxEditor.setSizePolicy(sizePolicy)
        self.fontComboBoxEditor.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.fontComboBoxEditor.setObjectName("fontComboBoxEditor")
        self.horizontalLayout_3.addWidget(self.fontComboBoxEditor)
        self.label_5 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.spinBoxEditor = QtWidgets.QSpinBox(self.groupBoxFontColorEditor)
        self.spinBoxEditor.setMinimumSize(QtCore.QSize(51, 26))
        self.spinBoxEditor.setMaximumSize(QtCore.QSize(51, 26))
        self.spinBoxEditor.setMinimum(6)
        self.spinBoxEditor.setMaximum(99)
        self.spinBoxEditor.setProperty("value", 10)
        self.spinBoxEditor.setObjectName("spinBoxEditor")
        self.horizontalLayout_3.addWidget(self.spinBoxEditor)
        self.gridLayout_141.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_7 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_7.setObjectName("label_7")
        self.gridLayout_13.addWidget(self.label_7, 0, 0, 1, 1)
        self.defaultFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.defaultFontColorEditor.setText("")
        self.defaultFontColorEditor.setObjectName("defaultFontColorEditor")
        self.gridLayout_13.addWidget(self.defaultFontColorEditor, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_8.setObjectName("label_8")
        self.gridLayout_13.addWidget(self.label_8, 0, 2, 1, 1)
        self.keywordFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.keywordFontColorEditor.setText("")
        self.keywordFontColorEditor.setObjectName("keywordFontColorEditor")
        self.gridLayout_13.addWidget(self.keywordFontColorEditor, 0, 3, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_27.setObjectName("label_27")
        self.gridLayout_13.addWidget(self.label_27, 0, 4, 1, 1)
        self.classFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.classFontColorEditor.setText("")
        self.classFontColorEditor.setObjectName("classFontColorEditor")
        self.gridLayout_13.addWidget(self.classFontColorEditor, 0, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_11.setObjectName("label_11")
        self.gridLayout_13.addWidget(self.label_11, 1, 0, 1, 1)
        self.methodFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.methodFontColorEditor.setText("")
        self.methodFontColorEditor.setObjectName("methodFontColorEditor")
        self.gridLayout_13.addWidget(self.methodFontColorEditor, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_9.setObjectName("label_9")
        self.gridLayout_13.addWidget(self.label_9, 1, 2, 1, 1)
        self.decorFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.decorFontColorEditor.setText("")
        self.decorFontColorEditor.setObjectName("decorFontColorEditor")
        self.gridLayout_13.addWidget(self.decorFontColorEditor, 1, 3, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_56.setObjectName("label_56")
        self.gridLayout_13.addWidget(self.label_56, 1, 4, 1, 1)
        self.numberFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.numberFontColorEditor.setText("")
        self.numberFontColorEditor.setObjectName("numberFontColorEditor")
        self.gridLayout_13.addWidget(self.numberFontColorEditor, 1, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_10.setObjectName("label_10")
        self.gridLayout_13.addWidget(self.label_10, 2, 0, 1, 1)
        self.commentFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.commentFontColorEditor.setText("")
        self.commentFontColorEditor.setObjectName("commentFontColorEditor")
        self.gridLayout_13.addWidget(self.commentFontColorEditor, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_12.setObjectName("label_12")
        self.gridLayout_13.addWidget(self.label_12, 2, 2, 1, 1)
        self.commentBlockFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.commentBlockFontColorEditor.setText("")
        self.commentBlockFontColorEditor.setObjectName("commentBlockFontColorEditor")
        self.gridLayout_13.addWidget(self.commentBlockFontColorEditor, 2, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_25.setObjectName("label_25")
        self.gridLayout_13.addWidget(self.label_25, 4, 4, 1, 1)
        self.cursorColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.cursorColorEditor.setText("")
        self.cursorColorEditor.setObjectName("cursorColorEditor")
        self.gridLayout_13.addWidget(self.cursorColorEditor, 4, 5, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_23.setObjectName("label_23")
        self.gridLayout_13.addWidget(self.label_23, 2, 4, 1, 1)
        self.caretLineColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.caretLineColorEditor.setText("")
        self.caretLineColorEditor.setObjectName("caretLineColorEditor")
        self.gridLayout_13.addWidget(self.caretLineColorEditor, 2, 5, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_32.setObjectName("label_32")
        self.gridLayout_13.addWidget(self.label_32, 3, 0, 1, 1)
        self.singleQuoteFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.singleQuoteFontColorEditor.setText("")
        self.singleQuoteFontColorEditor.setObjectName("singleQuoteFontColorEditor")
        self.gridLayout_13.addWidget(self.singleQuoteFontColorEditor, 3, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_33.setObjectName("label_33")
        self.gridLayout_13.addWidget(self.label_33, 3, 2, 1, 1)
        self.doubleQuoteFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.doubleQuoteFontColorEditor.setText("")
        self.doubleQuoteFontColorEditor.setObjectName("doubleQuoteFontColorEditor")
        self.gridLayout_13.addWidget(self.doubleQuoteFontColorEditor, 3, 3, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_34.setObjectName("label_34")
        self.gridLayout_13.addWidget(self.label_34, 4, 0, 1, 1)
        self.tripleSingleQuoteFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.tripleSingleQuoteFontColorEditor.setText("")
        self.tripleSingleQuoteFontColorEditor.setObjectName("tripleSingleQuoteFontColorEditor")
        self.gridLayout_13.addWidget(self.tripleSingleQuoteFontColorEditor, 4, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_35.setObjectName("label_35")
        self.gridLayout_13.addWidget(self.label_35, 4, 2, 1, 1)
        self.tripleDoubleQuoteFontColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.tripleDoubleQuoteFontColorEditor.setText("")
        self.tripleDoubleQuoteFontColorEditor.setObjectName("tripleDoubleQuoteFontColorEditor")
        self.gridLayout_13.addWidget(self.tripleDoubleQuoteFontColorEditor, 4, 3, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_40.setObjectName("label_40")
        self.gridLayout_13.addWidget(self.label_40, 5, 4, 1, 1)
        self.edgeColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.edgeColorEditor.setText("")
        self.edgeColorEditor.setObjectName("edgeColorEditor")
        self.gridLayout_13.addWidget(self.edgeColorEditor, 5, 5, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_45.setObjectName("label_45")
        self.gridLayout_13.addWidget(self.label_45, 5, 0, 1, 1)
        self.marginBackgroundColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.marginBackgroundColorEditor.setText("")
        self.marginBackgroundColorEditor.setObjectName("marginBackgroundColorEditor")
        self.gridLayout_13.addWidget(self.marginBackgroundColorEditor, 5, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_46.setObjectName("label_46")
        self.gridLayout_13.addWidget(self.label_46, 5, 2, 1, 1)
        self.marginForegroundColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.marginForegroundColorEditor.setText("")
        self.marginForegroundColorEditor.setObjectName("marginForegroundColorEditor")
        self.gridLayout_13.addWidget(self.marginForegroundColorEditor, 5, 3, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_47.setObjectName("label_47")
        self.gridLayout_13.addWidget(self.label_47, 6, 4, 1, 1)
        self.foldColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.foldColorEditor.setText("")
        self.foldColorEditor.setObjectName("foldColorEditor")
        self.gridLayout_13.addWidget(self.foldColorEditor, 6, 5, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_51.setObjectName("label_51")
        self.gridLayout_13.addWidget(self.label_51, 6, 0, 1, 1)
        self.selectionBackgroundColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.selectionBackgroundColorEditor.setText("")
        self.selectionBackgroundColorEditor.setObjectName("selectionBackgroundColorEditor")
        self.gridLayout_13.addWidget(self.selectionBackgroundColorEditor, 6, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_52.setObjectName("label_52")
        self.gridLayout_13.addWidget(self.label_52, 6, 2, 1, 1)
        self.selectionForegroundColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.selectionForegroundColorEditor.setText("")
        self.selectionForegroundColorEditor.setObjectName("selectionForegroundColorEditor")
        self.gridLayout_13.addWidget(self.selectionForegroundColorEditor, 6, 3, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_53.setObjectName("label_53")
        self.gridLayout_13.addWidget(self.label_53, 7, 0, 1, 1)
        self.matchedBraceBackgroundColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.matchedBraceBackgroundColorEditor.setText("")
        self.matchedBraceBackgroundColorEditor.setObjectName("matchedBraceBackgroundColorEditor")
        self.gridLayout_13.addWidget(self.matchedBraceBackgroundColorEditor, 7, 1, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_61.setObjectName("label_61")
        self.gridLayout_13.addWidget(self.label_61, 7, 2, 1, 1)
        self.matchedBraceForegroundColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.matchedBraceForegroundColorEditor.setText("")
        self.matchedBraceForegroundColorEditor.setObjectName("matchedBraceForegroundColorEditor")
        self.gridLayout_13.addWidget(self.matchedBraceForegroundColorEditor, 7, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBoxFontColorEditor)
        self.label_21.setObjectName("label_21")
        self.gridLayout_13.addWidget(self.label_21, 3, 4, 1, 1)
        self.paperBackgroundColorEditor = QgsColorButton(self.groupBoxFontColorEditor)
        self.paperBackgroundColorEditor.setText("")
        self.paperBackgroundColorEditor.setObjectName("paperBackgroundColorEditor")
        self.gridLayout_13.addWidget(self.paperBackgroundColorEditor, 3, 5, 1, 1)
        self.gridLayout_141.addLayout(self.gridLayout_13, 1, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.resetFontColorEditor = QtWidgets.QToolButton(self.groupBoxFontColorEditor)
        self.resetFontColorEditor.setText("")
        self.resetFontColorEditor.setAutoRaise(True)
        self.resetFontColorEditor.setObjectName("resetFontColorEditor")
        self.verticalLayout_5.addWidget(self.resetFontColorEditor)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.gridLayout_141.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBoxFontColorEditor, 1, 0, 1, 1)
        self.groupBoxAutoCompletionEditor = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxAutoCompletionEditor.setCheckable(True)
        self.groupBoxAutoCompletionEditor.setChecked(True)
        self.groupBoxAutoCompletionEditor.setProperty("collapsed", True)
        self.groupBoxAutoCompletionEditor.setProperty("saveCheckedState", True)
        self.groupBoxAutoCompletionEditor.setProperty("saveCollapsedState", True)
        self.groupBoxAutoCompletionEditor.setObjectName("groupBoxAutoCompletionEditor")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxAutoCompletionEditor)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBoxAutoCompletionEditor)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.autoCompThresholdEditor = QtWidgets.QSpinBox(self.groupBoxAutoCompletionEditor)
        self.autoCompThresholdEditor.setMaximum(10)
        self.autoCompThresholdEditor.setProperty("value", 2)
        self.autoCompThresholdEditor.setObjectName("autoCompThresholdEditor")
        self.gridLayout_4.addWidget(self.autoCompThresholdEditor, 0, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBoxAutoCompletionEditor)
        self.label_37.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.label_37, 0, 2, 1, 1)
        self.layoutRadioButtonEditor = QtWidgets.QGridLayout()
        self.layoutRadioButtonEditor.setObjectName("layoutRadioButtonEditor")
        self.autoCompFromDocEditor = QtWidgets.QRadioButton(self.groupBoxAutoCompletionEditor)
        self.autoCompFromDocEditor.setObjectName("autoCompFromDocEditor")
        self.layoutRadioButtonEditor.addWidget(self.autoCompFromDocEditor, 0, 0, 1, 1)
        self.autoCompFromDocAPIEditor = QtWidgets.QRadioButton(self.groupBoxAutoCompletionEditor)
        self.autoCompFromDocAPIEditor.setObjectName("autoCompFromDocAPIEditor")
        self.layoutRadioButtonEditor.addWidget(self.autoCompFromDocAPIEditor, 0, 2, 1, 1)
        self.autoCompFromAPIEditor = QtWidgets.QRadioButton(self.groupBoxAutoCompletionEditor)
        self.autoCompFromAPIEditor.setChecked(True)
        self.autoCompFromAPIEditor.setObjectName("autoCompFromAPIEditor")
        self.layoutRadioButtonEditor.addWidget(self.autoCompFromAPIEditor, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.layoutRadioButtonEditor, 1, 0, 1, 3)
        self.gridLayout_10.addWidget(self.groupBoxAutoCompletionEditor, 2, 0, 1, 1)
        self.groupBox_5 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_5.setProperty("collapsed", True)
        self.groupBox_5.setProperty("saveCollapsedState", True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.autoCloseBracketEditor = QtWidgets.QCheckBox(self.groupBox_5)
        self.autoCloseBracketEditor.setObjectName("autoCloseBracketEditor")
        self.verticalLayout_3.addWidget(self.autoCloseBracketEditor)
        self.autoInsertionImportEditor = QtWidgets.QCheckBox(self.groupBox_5)
        self.autoInsertionImportEditor.setObjectName("autoInsertionImportEditor")
        self.verticalLayout_3.addWidget(self.autoInsertionImportEditor)
        self.gridLayout_12.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox_5, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem3, 5, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_6.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.preloadAPI = QtWidgets.QCheckBox(self.groupBox_2)
        self.preloadAPI.setChecked(True)
        self.preloadAPI.setObjectName("preloadAPI")
        self.gridLayout_7.addWidget(self.preloadAPI, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.addAPIpath = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addAPIpath.sizePolicy().hasHeightForWidth())
        self.addAPIpath.setSizePolicy(sizePolicy)
        self.addAPIpath.setMinimumSize(QtCore.QSize(32, 32))
        self.addAPIpath.setMaximumSize(QtCore.QSize(32, 32))
        self.addAPIpath.setText("")
        self.addAPIpath.setObjectName("addAPIpath")
        self.verticalLayout.addWidget(self.addAPIpath)
        self.removeAPIpath = QtWidgets.QPushButton(self.groupBox_2)
        self.removeAPIpath.setMinimumSize(QtCore.QSize(32, 32))
        self.removeAPIpath.setMaximumSize(QtCore.QSize(32, 32))
        self.removeAPIpath.setText("")
        self.removeAPIpath.setObjectName("removeAPIpath")
        self.verticalLayout.addWidget(self.removeAPIpath)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.groupBoxPreparedAPI = QgsCollapsibleGroupBox(self.groupBox_2)
        self.groupBoxPreparedAPI.setCheckable(True)
        self.groupBoxPreparedAPI.setChecked(False)
        self.groupBoxPreparedAPI.setProperty("collapsed", True)
        self.groupBoxPreparedAPI.setProperty("saveCollapsedState", True)
        self.groupBoxPreparedAPI.setProperty("saveCheckedState", True)
        self.groupBoxPreparedAPI.setObjectName("groupBoxPreparedAPI")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxPreparedAPI)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.compileAPIs = QtWidgets.QPushButton(self.groupBoxPreparedAPI)
        self.compileAPIs.setObjectName("compileAPIs")
        self.gridLayout_3.addWidget(self.compileAPIs, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBoxPreparedAPI)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 27))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBoxPreparedAPI, 2, 0, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingsDialogPythonConsole)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 1, 1, 1)

        self.retranslateUi(SettingsDialogPythonConsole)
        self.stackedWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(SettingsDialogPythonConsole.accept)
        self.buttonBox.rejected.connect(SettingsDialogPythonConsole.reject)
        self.mOptionsListWidget.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialogPythonConsole)

    def retranslateUi(self, SettingsDialogPythonConsole):
        _translate = QtCore.QCoreApplication.translate
        __sortingEnabled = self.mOptionsListWidget.isSortingEnabled()
        self.mOptionsListWidget.setSortingEnabled(False)
        item = self.mOptionsListWidget.item(0)
        item.setText(_translate("SettingsDialogPythonConsole", "Console"))
        item.setToolTip(_translate("SettingsDialogPythonConsole", "Console settings"))
        item = self.mOptionsListWidget.item(1)
        item.setText(_translate("SettingsDialogPythonConsole", "Editor"))
        item.setToolTip(_translate("SettingsDialogPythonConsole", "Editor settings"))
        item = self.mOptionsListWidget.item(2)
        item.setText(_translate("SettingsDialogPythonConsole", "APIs"))
        item.setToolTip(_translate("SettingsDialogPythonConsole", " APIs file settings for autocompletion"))
        self.mOptionsListWidget.setSortingEnabled(__sortingEnabled)
        self.groupBoxFontColor.setTitle(_translate("SettingsDialogPythonConsole", "Font and Colors"))
        self.label.setText(_translate("SettingsDialogPythonConsole", "Font"))
        self.label_3.setText(_translate("SettingsDialogPythonConsole", "Size"))
        self.label_16.setText(_translate("SettingsDialogPythonConsole", "Default"))
        self.label_17.setText(_translate("SettingsDialogPythonConsole", "Keyword"))
        self.label_26.setText(_translate("SettingsDialogPythonConsole", "Class name"))
        self.label_13.setText(_translate("SettingsDialogPythonConsole", "Function"))
        self.label_18.setText(_translate("SettingsDialogPythonConsole", "Decorator"))
        self.label_55.setText(_translate("SettingsDialogPythonConsole", "Number"))
        self.label_19.setText(_translate("SettingsDialogPythonConsole", "Comment"))
        self.label_20.setText(_translate("SettingsDialogPythonConsole", "Comment block"))
        self.label_24.setText(_translate("SettingsDialogPythonConsole", "Cursor"))
        self.label_22.setText(_translate("SettingsDialogPythonConsole", "Caretline"))
        self.label_28.setText(_translate("SettingsDialogPythonConsole", "Single quote"))
        self.label_31.setText(_translate("SettingsDialogPythonConsole", "Double quote"))
        self.label_29.setText(_translate("SettingsDialogPythonConsole", "Triple single quote"))
        self.label_30.setText(_translate("SettingsDialogPythonConsole", "Triple double quote"))
        self.label_15.setText(_translate("SettingsDialogPythonConsole", "Background"))
        self.label_42.setText(_translate("SettingsDialogPythonConsole", "Margin background"))
        self.label_43.setText(_translate("SettingsDialogPythonConsole", "Margin foreground"))
        self.label_14.setText(_translate("SettingsDialogPythonConsole", "Error"))
        self.label_48.setText(_translate("SettingsDialogPythonConsole", "Selection background"))
        self.label_49.setText(_translate("SettingsDialogPythonConsole", "Selection foreground"))
        self.label_50.setText(_translate("SettingsDialogPythonConsole", "Brace background"))
        self.label_60.setText(_translate("SettingsDialogPythonConsole", "Brace foreground"))
        self.resetFontColor.setToolTip(_translate("SettingsDialogPythonConsole", "Reset to default colors"))
        self.groupBoxAutoCompletion.setTitle(_translate("SettingsDialogPythonConsole", "Autocompletion"))
        self.label_6.setText(_translate("SettingsDialogPythonConsole", "Autocompletion threshold"))
        self.label_36.setText(_translate("SettingsDialogPythonConsole", "characters"))
        self.autoCompFromDocAPI.setToolTip(_translate("SettingsDialogPythonConsole", "Get autocompletion from current document and installed APIs"))
        self.autoCompFromDocAPI.setText(_translate("SettingsDialogPythonConsole", "From doc and APIs"))
        self.autoCompFromAPI.setToolTip(_translate("SettingsDialogPythonConsole", "Get autocompletion from installed APIs"))
        self.autoCompFromAPI.setText(_translate("SettingsDialogPythonConsole", "From API files"))
        self.autoCompFromDoc.setToolTip(_translate("SettingsDialogPythonConsole", "Get autocompletion from current document"))
        self.autoCompFromDoc.setText(_translate("SettingsDialogPythonConsole", "From document"))
        self.groupBox_4.setTitle(_translate("SettingsDialogPythonConsole", "Typing"))
        self.autoCloseBracket.setText(_translate("SettingsDialogPythonConsole", "Automatic parentheses insertion"))
        self.autoInsertionImport.setText(_translate("SettingsDialogPythonConsole", "Automatic insertion of the \'import\' string on \'from xxx\'"))
        self.groupBoxRunDebugEditor.setTitle(_translate("SettingsDialogPythonConsole", "Run and Debug"))
        self.enableObjectInspector.setText(_translate("SettingsDialogPythonConsole", "Enable Object Inspector (switching between tabs may be slow)"))
        self.autoSaveScript.setText(_translate("SettingsDialogPythonConsole", "Auto-save script before running"))
        self.groupBoxFontColorEditor.setTitle(_translate("SettingsDialogPythonConsole", "Font and Colors"))
        self.label_4.setText(_translate("SettingsDialogPythonConsole", "Font"))
        self.label_5.setText(_translate("SettingsDialogPythonConsole", "Size"))
        self.label_7.setText(_translate("SettingsDialogPythonConsole", "Default"))
        self.label_8.setText(_translate("SettingsDialogPythonConsole", "Keyword"))
        self.label_27.setText(_translate("SettingsDialogPythonConsole", "Class name"))
        self.label_11.setText(_translate("SettingsDialogPythonConsole", "Function"))
        self.label_9.setText(_translate("SettingsDialogPythonConsole", "Decorator"))
        self.label_56.setText(_translate("SettingsDialogPythonConsole", "Number"))
        self.label_10.setText(_translate("SettingsDialogPythonConsole", "Comment"))
        self.label_12.setText(_translate("SettingsDialogPythonConsole", "Comment block"))
        self.label_25.setText(_translate("SettingsDialogPythonConsole", "Cursor"))
        self.label_23.setText(_translate("SettingsDialogPythonConsole", "Caretline"))
        self.label_32.setText(_translate("SettingsDialogPythonConsole", "Single quote"))
        self.label_33.setText(_translate("SettingsDialogPythonConsole", "Double quote"))
        self.label_34.setText(_translate("SettingsDialogPythonConsole", "Triple single quote"))
        self.label_35.setText(_translate("SettingsDialogPythonConsole", "Triple double quote"))
        self.label_40.setText(_translate("SettingsDialogPythonConsole", "Edge"))
        self.label_45.setText(_translate("SettingsDialogPythonConsole", "Margin background"))
        self.label_46.setText(_translate("SettingsDialogPythonConsole", "Margin foreground"))
        self.label_47.setText(_translate("SettingsDialogPythonConsole", "Fold guide"))
        self.label_51.setText(_translate("SettingsDialogPythonConsole", "Selection background"))
        self.label_52.setText(_translate("SettingsDialogPythonConsole", "Selection foreground"))
        self.label_53.setText(_translate("SettingsDialogPythonConsole", "Brace background"))
        self.label_61.setText(_translate("SettingsDialogPythonConsole", "Brace foreground"))
        self.label_21.setText(_translate("SettingsDialogPythonConsole", "Background"))
        self.resetFontColorEditor.setToolTip(_translate("SettingsDialogPythonConsole", "Reset to default colors"))
        self.groupBoxAutoCompletionEditor.setTitle(_translate("SettingsDialogPythonConsole", "Autocompletion"))
        self.label_2.setText(_translate("SettingsDialogPythonConsole", "Autocompletion threshold"))
        self.label_37.setText(_translate("SettingsDialogPythonConsole", "characters"))
        self.autoCompFromDocEditor.setToolTip(_translate("SettingsDialogPythonConsole", "Get autocompletion from current document"))
        self.autoCompFromDocEditor.setText(_translate("SettingsDialogPythonConsole", "From document"))
        self.autoCompFromDocAPIEditor.setToolTip(_translate("SettingsDialogPythonConsole", "Get autocompletion from current document and installed APIs"))
        self.autoCompFromDocAPIEditor.setText(_translate("SettingsDialogPythonConsole", "From doc and APIs"))
        self.autoCompFromAPIEditor.setToolTip(_translate("SettingsDialogPythonConsole", "Get autocompletion from installed APIs"))
        self.autoCompFromAPIEditor.setText(_translate("SettingsDialogPythonConsole", "From API files"))
        self.groupBox_5.setTitle(_translate("SettingsDialogPythonConsole", "Typing"))
        self.autoCloseBracketEditor.setText(_translate("SettingsDialogPythonConsole", "Automatic parentheses insertion"))
        self.autoInsertionImportEditor.setText(_translate("SettingsDialogPythonConsole", "Automatic insertion of the \'import\' string on \'from xxx\'"))
        self.groupBox_2.setTitle(_translate("SettingsDialogPythonConsole", "APIs"))
        self.preloadAPI.setText(_translate("SettingsDialogPythonConsole", "Using preloaded APIs file"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SettingsDialogPythonConsole", "APIs"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SettingsDialogPythonConsole", "Path"))
        self.groupBoxPreparedAPI.setTitle(_translate("SettingsDialogPythonConsole", "Using prepared APIs file"))
        self.compileAPIs.setText(_translate("SettingsDialogPythonConsole", "Compile APIs…"))

from qgis.gui import QgsCollapsibleGroupBox, QgsColorButton
